version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: monthly
    time: "12:00"
    timezone: America/Edmonton
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: vite
    versions:
    - 2.0.0-alpha.5
    - 2.0.0-beta.61
    - 2.0.4
  - dependency-name: "@vue/compiler-sfc"
    versions:
    - 3.0.5
    - 3.0.7
  - dependency-name: eslint
    versions:
    - 7.16.0
    - 7.19.0
    - 7.21.0
  - dependency-name: vue-router
    versions:
    - 4.0.2
    - 4.0.3
    - 4.0.4
  - dependency-name: lint-staged
    versions:
    - 10.5.3
  - dependency-name: lodash
    versions:
    - 4.17.20
